### ISSUE TITLE
[BUG] Configuration contains dependency cycles

### ISSUE THREAD

**Issue by pablosoria** [compose-generator/compose-generator#569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In Windows 10 with Ubuntu WSL and Docker Desktop.
After generating a project with compose generator with nginx, php and mongo I try to remove a service and get the error: Configuration contains dependency cycles
In Ubuntu WSL:
````powershell
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/cg/out chillibits/compose-generator remove
ERROR: 2024/07/23 12:04:02 Configuration contains dependency cycles
````

.cg.yml
````yml
advanced-config: false
created-at: 1721730036794262046
created-by: root
modified-at: 1721730674525493315
modified-by: root
production-ready: false
project-container-name: phpandmongo
project-name: phpAndMongo
````
docker-compose.yml empty

### Expected Behavior

I don't know what the expected behavior is, I guess it should show a list with the services available to delete or the option to write which one to delete.

### Steps To Reproduce

I tried 
````powershell
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/cg/out chillibits/compose-generator remove
````
and
````powershell
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/cg/out chillibits/compose-generator remove php
````

### Environment

```markdown
- OS: Windows 10
- Installation method: docker container through Ubuntu WSL with Docker Desktop
- Compose Generator version: 1.9
```

**Comment by marcauberer** [comment]
Can you share the resulting compose file?

**Comment by pablosoria** [comment]
> Can you share the resulting compose file?

docker-compose.yml
````yaml
services:
  backend-php:
    build:
      context: ./backend-php
    container_name: phpandmongo-backend-php
    depends_on:
      database-mongodb:
        condition: service_started
    ports:
    - mode: ingress
      target: 80
      published: "81"
      protocol: tcp
    restart: always
  database-mongodb:
    container_name: phpandmongo-db-mongodb
    env_file:
    - environment.env
    image: mongo:5.0
    networks:
      backend-database: null
    ports:
    - mode: ingress
      target: 27017
      published: "27017"
      protocol: tcp
    restart: always
    volumes:
    - type: bind
      source: ./volumes/mongodb-config
      target: /data/configdb
    - type: bind
      source: ./volumes/mongodb-config
      target: /var/lib/mongodb
    - type: bind
      source: ./volumes/mongodb-data
      target: /data/db
    - type: bind
      source: ./volumes/mongodb-init
      target: /docker-entrypoint-initdb.d
  frontend-common-website:
    build:
      context: ./frontend-website
    container_name: phpandmongo-frontend-nginx
    depends_on:
      backend-php:
        condition: service_started
      database-mongodb:
        condition: service_started
    ports:
    - mode: ingress
      target: 80
      published: "80"
      protocol: tcp
    restart: always
networks:
  backend-database: {}

````
